### PR TITLE
519 - use SmtSolverError for all Smt-related errors in booster

### LINKED ISSUE #519: Use SmtSolverError for SMT-related errors in booster
The current code related to SMT solver bindings calls `error` when SMT solver errors happen. These errors become `RuntimeError`s in the response.

Instead, we should use the dedicated `SmtSolverError` code.

### PR DESCRIPTION
**Pull request by jberthold**
As in the legacy backend, the SMT errors are caught at the top level in a handler. 
An `SMTError` is thrown generally when there is a problem with solver operations.

Undecided predicates during rewriting and simplifications are reported back to the client as `SMTSolverError` (code 5) and include the predicates in play in the `data` field. Other errors are reported as runtime errors.
As in the legacy backend, we lose all rewriting/simplification work done prior to the SMT error.

Fixes #519 

## Summary by CodeRabbit

- **New Features**
	- Introduced enhanced error handling for SMT operations, including specific error messages and responses.
	- Added a new `SetTimeout` feature to control solver operation timeout settings.
- **Bug Fixes**
	- Improved SMT error handling with the addition of `handleSmtError` function, ensuring more robust and informative error responses.
- **Refactor**
	- Updated various modules to improve error handling logic and to support new timeout control feature.
- **Tests**
	- Added a new test case to validate the handling of unknown states in SMT model generation.

### CODE REVIEW

**Review by geo2a — APPROVED** [review]

**Comment by jberthold** [comment]
Should be discussed whether or not to amend this to return the undecided predicate (and make other SMT errors general `RuntimeError`s as they were previously. See https://github.com/runtimeverification/kontrol/issues/396

**Comment by jberthold** [comment]
## KEVM tests - no significant change

| Test                                                                 | 519-use-SmtSolverError-in-booster time | master-618360c time | (519-use-SmtSolverError-in-booster/master-618360c) time 
|----------------------------------------------------------------------|----------------------------------------|---------------------|---------------------------------------------------------
| kontrol/test-emitcontracttest-testexpectemit-0-spec.k                | 45.03                                  | 57.37               | 0.7849050026146069                                      
| kontrol/test-expectreverttest-testfail_expectrevert_bytes4-0-spec.k  | 51.25                                  | 61.67               | 0.8310361602075563                                      
| kontrol/test-storetest-teststoreload-0-spec.k                        | 96.21                                  | 103.19              | 0.9323577866072293                                      
| kontrol/test-owneruponlytest-testincrementasowner-0-spec.k           | 74.18                                  | 76.99               | 0.9635017534744773                                      
| kontrol/test-countertest-testincrement-0-spec.k                      | 100.33                                 | 89.64               | 1.1192547969656403                                      
| kontrol/test-storetest-testaccesses-0-spec.k                         | 59.41                                  | 51.82               | 1.1464685449633345                                      
| kontrol/test-expectreverttest-test_expectrevert_returnvalue-0-spec.k | 64.31                                  | 55.11               | 1.1669388495735802                                      
| TOTAL                                                                | 490.72                     | 495.79  | 0.98977389

**Comment by jberthold** [comment]
I modified the code to only use `SmtSolverError` when the solver returned `Unknown`  from a predicate check (matches the legacy backend behaviour), and fill the `data` field with the predicate in question (both premises and actual predicate to check.

Also implemented the `--smt-timeout` option which was previously parsed but ignored.

**Comment by jberthold** [comment]
Added the `get-model` test from `haskell-backend` PR https://github.com/runtimeverification/haskell-backend/pull/3737 .
A `simplify` test does _not_ produce an `SmtUnknownError` because booster does not currently use the SMT solver during simplification/evaluation.

**Comment by jberthold** [comment]
> * 55-62: The introduction of the `SMTError` data type with specific error variants (`GeneralSMTError`, `SMTTranslationError`, `SMTSolverUnknown`) is a significant improvement in error handling.

> * 200-204: The addition of Booster.handleSmtError to the list of error handlers in the jsonRpcServer function call is a critical change that aligns with the PR's objective to standardize SMT solver error handling. 

Yay, code rabbit, you got it right  :rabbit:  ! :stuck_out_tongue:

**Review by geo2a — APPROVED** [review]
Approved! I left a small suggestion about the new get model test case.

**Pull request merged**
