### PR TITLE
Better map unification

### PR DESCRIPTION
**Pull request by goodlyrottenapple**
Some more powerful map unification when keys match exactly, even if some keys are symbolic/function applications

### CODE REVIEW

**Comment by goodlyrottenapple** [comment]
```
➜  scripts git:(sam/better-map-unification) ✗ python3 compare.py logs/kevm-v1.0.372-sam-better-map-unification.log logs/kevm-v1.0.372-master-1b22ad4.log
| Test                                      | sam-better-map-unification time | master-1b22ad4 time | (sam-better-map-unification/master-1b22ad4) time
|-------------------------------------------|---------------------------------|---------------------|--------------------------------------------------
| mcd/flipper-bids-pass-rough-spec.k        | 167.59                          | 196.87              | 0.8512724132676386
| erc20/hkg/transfer-success-1-spec.k       | 73.48                           | 85.83               | 0.8561109169288128
| erc20/ds/approve-failure-spec.k           | 87.02                           | 100.61              | 0.8649239638206937
| bihu/forwardToHotWallet-success-2-spec.k  | 85.79                           | 94.62               | 0.9066793489748468
| benchmarks/storagevar02-nooverflow-spec.k | 65.17                           | 70.44               | 0.9251845542305509
| erc20/hkg/transferFrom-success-2-spec.k   | 83.39                           | 89.96               | 0.926967541129391
| bihu/forwardToHotWallet-success-1-spec.k  | 88.76                           | 95.48               | 0.9296187683284458
| erc20/hkg/transfer-success-2-spec.k       | 68.12                           | 73.26               | 0.9298389298389298
| benchmarks/dynamicarray00-spec.k          | 65.26                           | 69.84               | 0.9344215349369989
| erc20/ds/transferFrom-success-1-spec.k    | 140.06                          | 149.04              | 0.939747718733226
| erc20/hkg/transferFrom-success-1-spec.k   | 103.59                          | 110.06              | 0.941213883336362
| erc20/ds/transferFrom-success-2-spec.k    | 112.82                          | 119.54              | 0.9437845072778985
| mcd/flopper-cage-pass-spec.k              | 93.17                           | 97.99               | 0.9508113072762527
| mcd/flopper-file-pass-rough-spec.k        | 595.01                          | 623.07              | 0.9549649317091177
| mcd/dsvalue-read-pass-spec.k              | 79.68                           | 83.29               | 0.9566574618801778
| erc20/ds/transferFrom-failure-1-b-spec.k  | 206.92                          | 216.29              | 0.9566785334504601
| mcd/cat-file-addr-pass-rough-spec.k       | 90.77                           | 94.83               | 0.9571865443425076
| erc20/ds/transferFrom-failure-1-a-spec.k  | 115.62                          | 120.63              | 0.9584680427754291
| mcd/vat-addui-pass-spec.k                 | 257.38                          | 267.26              | 0.9630322532365487
| erc20/ds/transfer-failure-1-a-spec.k      | 93.98                           | 97.47               | 0.9641941110085155
| benchmarks/ecrecover00-siginvalid-spec.k  | 116.11                          | 110.26              | 1.0530564121168147
| benchmarks/encode-keccak00-spec.k         | 77.47                           | 73.46               | 1.0545875306289139
| erc20/ds/transfer-success-2-spec.k        | 98.57                           | 90.61               | 1.087849023286613
| erc20/hkg/allowance-spec.k                | 85.11                           | 71.63               | 1.1881893061566384
| TOTAL                                     | 3050.84                         | 3202.34             | 0.9526908448197255
```

**Review by geo2a — APPROVED** [review]

**Comment by geo2a** [comment]
As we've discussed, the data comes out noisy. I've re-run all tests with `PYTEST_PARALLEL=2`, and some of the slowed-down tests are now even in my table. We need to do something about the test-suite. Posting the full data for reference.

**Kontrol**
| Test                                                                       | sam-better-map-unification time | master-1b22ad4 time | (sam-better-map-unification/master-1b22ad4) time
|----------------------------------------------------------------------------|---------------------------------|---------------------|--------------------------------------------------
| ExpectRevertTest.testFail_ExpectRevert_failAndSuccess()                    | 123.39                          | 156.64              | 0.7877298263534219
| EmitContractTest.testExpectEmitDoNotCheckData()                            | 112.44                          | 141.32              | 0.795641098216813
| Empty.sol                                                                  | 54.54                           | 64.69               | 0.8430978512907714
| ArithmeticTest.test_max2(uint256,uint256)                                  | 102.0                           | 115.78              | 0.8809811711867335
| ERC20.sol                                                                  | 56.19                           | 63.69               | 0.8822421102213849
| ERC721.sol                                                                 | 55.48                           | 62.67               | 0.8852720599968086
| InitCodeTest.testFail_init()                                               | 161.54                          | 179.14              | 0.9017528190242269
| UintTypeTest.test_uint256(uint256)                                         | 55.23                           | 60.98               | 0.905706789111184
| ExpectRevertTest.testFail_expectRevert_empty()                             | 68.88                           | 75.03               | 0.9180327868852458
| src/tests/integration/test_foundry_prove.py::test_foundry_auto_abstraction | 57.99                           | 62.4                | 0.9293269230769231
| ArithmeticTest.test_max1(uint256,uint256)                                  | 106.12                          | 113.89              | 0.9317762753534112
| ExpectRevertTest.test_expectRevert_true()                                  | 122.92                          | 131.62              | 0.9339006230056223
| AssumeTest.test_multi_assume(address,address)                              | 150.43                          | 160.08              | 0.9397176411794103
| AssertTest.test_assert_true()                                              | 81.56                           | 86.78               | 0.9398478912191749
| AccountParamsTest.testDealConcrete()                                       | 70.09                           | 74.56               | 0.9400482832618026
| AddrTest.test_builtInAddresses()                                           | 52.5                            | 55.83               | 0.940354648038689
| Setup2Test.testFail_setup()                                                | 119.89                          | 127.31              | 0.9417170685727752
| ExpectRevertTest.testFail_expectRevert_multipleReverts()                   | 151.96                          | 161.32              | 0.9419786759236302
| AssertTest.test_failing_branch(uint256)                                    | 104.22                          | 110.63              | 0.9420591159721595
| ExpectCallTest.testExpectRegularCall()                                     | 115.27                          | 122.11              | 0.943984931619032
| ExpectRevertTest.test_ExpectRevert_increasedDepth()                        | 197.59                          | 209.05              | 0.9451805788088974
| AssumeTest.test_assume_true(uint256,uint256)                               | 67.28                           | 71.04               | 0.947072072072072
| PlainPrankTest.test_startPrank_zeroAddress_true()                          | 171.13                          | 180.59              | 0.9476161470734813
| src/tests/integration/test_foundry_prove.py::test_foundry_remove_node      | 104.99                          | 110.76              | 0.9479053810039725
| AssumeTest.testFail_assume_false(uint256,uint256)                          | 72.95                           | 76.93               | 0.9482646561809437
| ExpectRevertTest.test_expectRevert_message()                               | 131.45                          | 138.6               | 0.9484126984126984
| BlockParamsTest.testCoinBase()                                             | 62.36                           | 65.66               | 0.9497410904660372
| BlockParamsTest.testChainId(uint256)                                       | 66.66                           | 70.15               | 0.9502494654312187
| BlockParamsTest.testBlockNumber()                                          | 51.7                            | 54.35               | 0.9512419503219871
| StoreTest.testGasLoadWarmUp()                                              | 91.02                           | 95.63               | 0.9517933702812925
| AssertTest.test_assert_true_branch(uint256)                                | 115.67                          | 121.46              | 0.9523299851803063
| PlainPrankTest.test_startPrankWithOrigin_true()                            | 169.19                          | 177.63              | 0.9524855035748466
| SymbolicStorageTest.testEmptyInitialStorage(uint256)                       | 67.25                           | 70.55               | 0.9532246633593197
| LabelTest.testLabel()                                                      | 61.82                           | 64.78               | 0.9543068848410003
| AccountParamsTest.test_Nonce_NonExistentAddress()                          | 83.68                           | 87.58               | 0.9554692852249373
| BlockParamsTest.testWarp(uint256)                                          | 67.75                           | 70.82               | 0.956650663654335
| AddrTest.test_notBuiltinAddress_concrete()                                 | 52.24                           | 54.58               | 0.9571271528032247
| EmitContractTest.testExpectEmit()                                          | 114.98                          | 119.94              | 0.9586459896614975
| ExpectCallTest.testExpectStaticCall()                                      | 117.28                          | 122.31              | 0.958874989780067
| ExpectRevertTest.test_expectRevert_internalCall()                          | 67.79                           | 70.69               | 0.9589758098740983
| PlainPrankTest.test_startPrank_true()                                      | 168.87                          | 176.05              | 0.959216131780744
| AccountParamsTest.test_GetNonce_true()                                     | 67.69                           | 70.55               | 0.9594613749114104
| StoreTest.testGasStoreColdVM()                                             | 67.86                           | 70.71               | 0.9596945269410269
| InitCodeTest.test_init()                                                   | 208.22                          | 216.94              | 0.9598045542546326
| src/tests/integration/test_foundry_prove.py::test_foundry_resume_proof     | 132.54                          | 138.04              | 0.9601564763836569
| AccountParamsTest.testDealSymbolic(uint256)                                | 73.8                            | 76.85               | 0.9603122966818478
| ExpectRevertTest.test_expectRevert_returnValue()                           | 172.18                          | 179.28              | 0.9603971441320839
| CounterTest.testIncrement()                                                | 186.75                          | 194.3               | 0.9611425630468348
| StoreTest.testLoadNonExistent()                                            | 68.14                           | 70.79               | 0.9625653340867354
| AssertTest.testFail_expect_revert()                                        | 77.32                           | 80.27               | 0.9632490345085336
| AccountParamsTest.test_getNonce_unknownSymbolic(address)                   | 127.79                          | 132.65              | 0.9633622314361101
| StoreTest.testGasLoadColdVM()                                              | 67.23                           | 69.76               | 0.9637327981651376
| BlockParamsTest.testRoll(uint256)                                          | 68.31                           | 70.87               | 0.96387752222379
| AssumeTest.test_assume_staticCall(bool)                                    | 75.0                            | 77.81               | 0.9638863899241742
| AssertTest.test_revert_branch(uint256,uint256)                             | 106.0                           | 109.72              | 0.966095515858549
| BMCLoopsTest.test_countdown_symbolic(uint256)                              | 210.43                          | 199.17              | 1.05653461866747
| PlainPrankTest.test_prank_zeroAddress_true()                               | 206.18                          | 194.09              | 1.0622906898861353
| CounterTest.testSetNumber(uint256)                                         | 216.7                           | 203.02              | 1.0673825238892718
| BytesTypeTest.test_bytes32(bytes32)                                        | 57.63                           | 53.93               | 1.068607454107176
| AllowChangesTest.testFailAllowCallsToAddress()                             | 192.14                          | 178.38              | 1.0771386926785513
| AllowChangesTest.testAllow()                                               | 197.26                          | 179.56              | 1.0985742927155269
| EmitContractTest.testExpectEmitCheckEmitter()                              | 134.59                          | 121.38              | 1.1088317680013182
| AccountParamsTest.testEtchConcrete()                                       | 144.07                          | 128.68              | 1.1195990052844265
| Storage.sol                                                                | 60.41                           | 53.12               | 1.1372364457831325
| StoreTest.testStoreLoad()                                                  | 132.53                          | 115.01              | 1.1523345796017737
| AccountParamsTest.testNonceSymbolic(uint64)                                | 140.83                          | 120.95              | 1.1643654402645722
| LoopsTest.test_sum_10()                                                    | 113.66                          | 97.48               | 1.1659827656955273
| SymbolicStorageTest.testFail_SymbolicStorage1(uint256)                     | 257.67                          | 220.1               | 1.170695138573376
| AssertTest.test_assert_false()                                             | 108.95                          | 91.86               | 1.1860439799695188
| SymbolicStorageTest.testFail_SymbolicStorage(uint256)                      | 221.97                          | 185.07              | 1.199384016858486
| Setup2Test.test_setup()                                                    | 86.26                           | 68.98               | 1.250507393447376
| StoreTest.testStoreLoadNonExistent()                                       | 102.35                          | 81.84               | 1.2506109481915932
| AddrTest.test_addr_true()                                                  | 82.94                           | 65.85               | 1.259529233105543
| AddrTest.test_notBuiltinAddress_symbolic(address)                          | 124.43                          | 88.03               | 1.4134953992956947
| TOTAL                                                                      | 8316.12                         | 8340.660000000003   | 0.9970577867938505| Test                                                                       | sam-better-map-unification time | master-1b22ad4 time | (sam-better-map-unification/master-1b22ad4) time
|----------------------------------------------------------------------------|---------------------------------|---------------------|--------------------------------------------------
| ExpectRevertTest.testFail_ExpectRevert_failAndSuccess()                    | 123.39                          | 156.64              | 0.7877298263534219
| EmitContractTest.testExpectEmitDoNotCheckData()                            | 112.44                          | 141.32              | 0.795641098216813
| Empty.sol                                                                  | 54.54                           | 64.69               | 0.8430978512907714
| ArithmeticTest.test_max2(uint256,uint256)                                  | 102.0                           | 115.78              | 0.8809811711867335
| ERC20.sol                                                                  | 56.19                           | 63.69               | 0.8822421102213849
| ERC721.sol                                                                 | 55.48                           | 62.67               | 0.8852720599968086
| InitCodeTest.testFail_init()                                               | 161.54                          | 179.14              | 0.9017528190242269
| UintTypeTest.test_uint256(uint256)                                         | 55.23                           | 60.98               | 0.905706789111184
| ExpectRevertTest.testFail_expectRevert_empty()                             | 68.88                           | 75.03               | 0.9180327868852458
| src/tests/integration/test_foundry_prove.py::test_foundry_auto_abstraction | 57.99                           | 62.4                | 0.9293269230769231
| ArithmeticTest.test_max1(uint256,uint256)                                  | 106.12                          | 113.89              | 0.9317762753534112
| ExpectRevertTest.test_expectRevert_true()                                  | 122.92                          | 131.62              | 0.9339006230056223
| AssumeTest.test_multi_assume(address,address)                              | 150.43                          | 160.08              | 0.9397176411794103
| AssertTest.test_assert_true()                                              | 81.56                           | 86.78               | 0.9398478912191749
| AccountParamsTest.testDealConcrete()                                       | 70.09                           | 74.56               | 0.9400482832618026
| AddrTest.test_builtInAddresses()                                           | 52.5                            | 55.83               | 0.940354648038689
| Setup2Test.testFail_setup()                                                | 119.89                          | 127.31              | 0.9417170685727752
| ExpectRevertTest.testFail_expectRevert_multipleReverts()                   | 151.96                          | 161.32              | 0.9419786759236302
| AssertTest.test_failing_branch(uint256)                                    | 104.22                          | 110.63              | 0.9420591159721595
| ExpectCallTest.testExpectRegularCall()                                     | 115.27                          | 122.11              | 0.943984931619032
| ExpectRevertTest.test_ExpectRevert_increasedDepth()                        | 197.59                          | 209.05              | 0.9451805788088974
| AssumeTest.test_assume_true(uint256,uint256)                               | 67.28                           | 71.04               | 0.947072072072072
| PlainPrankTest.test_startPrank_zeroAddress_true()                          | 171.13                          | 180.59              | 0.9476161470734813
| src/tests/integration/test_foundry_prove.py::test_foundry_remove_node      | 104.99                          | 110.76              | 0.9479053810039725
| AssumeTest.testFail_assume_false(uint256,uint256)                          | 72.95                           | 76.93               | 0.9482646561809437
| ExpectRevertTest.test_expectRevert_message()                               | 131.45                          | 138.6               | 0.9484126984126984
| BlockParamsTest.testCoinBase()                                             | 62.36                           | 65.66               | 0.9497410904660372
| BlockParamsTest.testChainId(uint256)                                       | 66.66                           | 70.15               | 0.9502494654312187
| BlockParamsTest.testBlockNumber()                                          | 51.7                            | 54.35               | 0.9512419503219871
| StoreTest.testGasLoadWarmUp()                                              | 91.02                           | 95.63               | 0.9517933702812925
| AssertTest.test_assert_true_branch(uint256)                                | 115.67                          | 121.46              | 0.9523299851803063
| PlainPrankTest.test_startPrankWithOrigin_true()                            | 169.19                          | 177.63              | 0.9524855035748466
| SymbolicStorageTest.testEmptyInitialStorage(uint256)                       | 67.25                           | 70.55               | 0.9532246633593197
| LabelTest.testLabel()                                                      | 61.82                           | 64.78               | 0.9543068848410003
| AccountParamsTest.test_Nonce_NonExistentAddress()                          | 83.68                           | 87.58               | 0.9554692852249373
| BlockParamsTest.testWarp(uint256)                                          | 67.75                           | 70.82               | 0.956650663654335
| AddrTest.test_notBuiltinAddress_concrete()                                 | 52.24                           | 54.58               | 0.9571271528032247
| EmitContractTest.testExpectEmit()                                          | 114.98                          | 119.94              | 0.9586459896614975
| ExpectCallTest.testExpectStaticCall()                                      | 117.28                          | 122.31              | 0.958874989780067
| ExpectRevertTest.test_expectRevert_internalCall()                          | 67.79                           | 70.69               | 0.9589758098740983
| PlainPrankTest.test_startPrank_true()                                      | 168.87                          | 176.05              | 0.959216131780744
| AccountParamsTest.test_GetNonce_true()                                     | 67.69                           | 70.55               | 0.9594613749114104
| StoreTest.testGasStoreColdVM()                                             | 67.86                           | 70.71               | 0.9596945269410269
| InitCodeTest.test_init()                                                   | 208.22                          | 216.94              | 0.9598045542546326
| src/tests/integration/test_foundry_prove.py::test_foundry_resume_proof     | 132.54                          | 138.04              | 0.9601564763836569
| AccountParamsTest.testDealSymbolic(uint256)                                | 73.8                            | 76.85               | 0.9603122966818478
| ExpectRevertTest.test_expectRevert_returnValue()                           | 172.18                          | 179.28              | 0.9603971441320839
| CounterTest.testIncrement()                                                | 186.75                          | 194.3               | 0.9611425630468348
| StoreTest.testLoadNonExistent()                                            | 68.14                           | 70.79               | 0.9625653340867354
| AssertTest.testFail_expect_revert()                                        | 77.32                           | 80.27               | 0.9632490345085336
| AccountParamsTest.test_getNonce_unknownSymbolic(address)                   | 127.79                          | 132.65              | 0.9633622314361101
| StoreTest.testGasLoadColdVM()                                              | 67.23                           | 69.76               | 0.9637327981651376
| BlockParamsTest.testRoll(uint256)                                          | 68.31                           | 70.87               | 0.96387752222379
| AssumeTest.test_assume_staticCall(bool)                                    | 75.0                            | 77.81               | 0.9638863899241742
| AssertTest.test_revert_branch(uint256,uint256)                             | 106.0                           | 109.72              | 0.966095515858549
| BMCLoopsTest.test_countdown_symbolic(uint256)                              | 210.43                          | 199.17              | 1.05653461866747
| PlainPrankTest.test_prank_zeroAddress_true()                               | 206.18                          | 194.09              | 1.0622906898861353
| CounterTest.testSetNumber(uint256)                                         | 216.7                           | 203.02              | 1.0673825238892718
| BytesTypeTest.test_bytes32(bytes32)                                        | 57.63                           | 53.93               | 1.068607454107176
| AllowChangesTest.testFailAllowCallsToAddress()                             | 192.14                          | 178.38              | 1.0771386926785513
| AllowChangesTest.testAllow()                                               | 197.26                          | 179.56              | 1.0985742927155269
| EmitContractTest.testExpectEmitCheckEmitter()                              | 134.59                          | 121.38              | 1.1088317680013182
| AccountParamsTest.testEtchConcrete()                                       | 144.07                          | 128.68              | 1.1195990052844265
| Storage.sol                                                                | 60.41                           | 53.12               | 1.1372364457831325
| StoreTest.testStoreLoad()                                                  | 132.53                          | 115.01              | 1.1523345796017737
| AccountParamsTest.testNonceSymbolic(uint64)                                | 140.83                          | 120.95              | 1.1643654402645722
| LoopsTest.test_sum_10()                                                    | 113.66                          | 97.48               | 1.1659827656955273
| SymbolicStorageTest.testFail_SymbolicStorage1(uint256)                     | 257.67                          | 220.1               | 1.170695138573376
| AssertTest.test_assert_false()                                             | 108.95                          | 91.86               | 1.1860439799695188
| SymbolicStorageTest.testFail_SymbolicStorage(uint256)                      | 221.97                          | 185.07              | 1.199384016858486
| Setup2Test.test_setup()                                                    | 86.26                           | 68.98               | 1.250507393447376
| StoreTest.testStoreLoadNonExistent()                                       | 102.35                          | 81.84               | 1.2506109481915932
| AddrTest.test_addr_true()                                                  | 82.94                           | 65.85               | 1.259529233105543
| AddrTest.test_notBuiltinAddress_symbolic(address)                          | 124.43                          | 88.03               | 1.4134953992956947
| TOTAL                                                                      | 8316.12                         | 8340.660000000003   | 0.9970577867938505

**KEVM**

| Test                                      | sam-better-map-unification time | master-1b22ad4 time | (sam-better-map-unification/master-1b22ad4) time
|-------------------------------------------|---------------------------------|---------------------|--------------------------------------------------
| mcd/vat-subui-pass-spec.k                 | 112.09                          | 234.49              | 0.47801612009040895
| erc20/ds/approve-success-spec.k           | 73.72                           | 91.82               | 0.8028751905902853
| benchmarks/storagevar02-overflow-spec.k   | 61.27                           | 73.18               | 0.8372506149221098
| benchmarks/storagevar01-spec.k            | 60.36                           | 71.65               | 0.8424284717376134
| erc20/ds/transfer-failure-1-a-spec.k      | 91.12                           | 107.42              | 0.8482591696145969
| mcd/flipper-bids-pass-rough-spec.k        | 158.11                          | 178.95              | 0.8835428890751608
| mcd/cat-file-addr-pass-rough-spec.k       | 76.56                           | 73.81               | 1.03725782414307
| erc20/ds/transferFrom-failure-2-b-spec.k  | 120.98                          | 116.33              | 1.0399724920484827
| mcd/vat-subui-pass-rough-spec.k           | 237.91                          | 228.57              | 1.0408627553922212
| erc20/ds/transferFrom-failure-1-d-spec.k  | 88.46                           | 84.93               | 1.041563640645237
| mcd/vat-slip-pass-rough-spec.k            | 302.05                          | 289.67              | 1.0427382883971417
| mcd/dsvalue-peek-pass-rough-spec.k        | 78.91                           | 75.61               | 1.043645020499934
| bihu/forwardToHotWallet-failure-2-spec.k  | 82.97                           | 79.49               | 1.043779091709649
| erc20/ds/transfer-failure-2-a-spec.k      | 85.7                            | 82.09               | 1.0439761237665977
| erc20/ds/transferFrom-success-2-spec.k    | 114.28                          | 109.39              | 1.0447024408081178
| mcd/vat-addui-pass-spec.k                 | 237.73                          | 227.38              | 1.0455185152607969
| erc20/ds/transferFrom-failure-1-a-spec.k  | 113.82                          | 108.76              | 1.0465244575211474
| mcd/flipper-ttl-pass-spec.k               | 78.04                           | 74.53               | 1.0470951294780626
| mcd/dstoken-approve-fail-rough-spec.k     | 134.24                          | 127.91              | 1.04948792119459
| erc20/ds/transferFrom-failure-2-a-spec.k  | 98.16                           | 93.51               | 1.0497273018928457
| benchmarks/storagevar03-spec.k            | 54.53                           | 51.87               | 1.0512820512820513
| erc20/hkg/approve-spec.k                  | 61.14                           | 58.15               | 1.0514187446259673
| benchmarks/overflow00-nooverflow-spec.k   | 55.02                           | 52.24               | 1.0532159264931087
| benchmarks/requires01-a0gt0-spec.k        | 55.65                           | 52.82               | 1.0535781900795154
| mcd/flipper-addu48u48-fail-rough-spec.k   | 87.73                           | 83.22               | 1.054193703436674
| mcd/end-subuu-pass-spec.k                 | 93.72                           | 88.87               | 1.0545740969956114
| mcd/vat-muluu-pass-spec.k                 | 188.93                          | 179.09              | 1.0549444413423419
| mcd/flipper-tau-pass-spec.k               | 76.55                           | 72.42               | 1.0570284451808891
| mcd/vat-addui-fail-rough-spec.k           | 164.35                          | 155.39              | 1.05766136817041
| mcd/vat-subui-fail-rough-spec.k           | 160.81                          | 151.95              | 1.0583086541625535
| mcd/dai-adduu-fail-rough-spec.k           | 82.67                           | 77.97               | 1.0602795947159165
| examples/storage-spec.md                  | 223.19                          | 210.37              | 1.0609402481342396
| erc20/ds/transfer-failure-2-b-spec.k      | 63.48                           | 59.73               | 1.0627825213460573
| erc20/ds/transfer-failure-1-c-spec.k      | 67.79                           | 63.71               | 1.0640401820750276
| erc20/hkg/totalSupply-spec.k              | 51.88                           | 48.72               | 1.0648604269293924
| erc20/ds/transferFrom-failure-2-c-spec.k  | 73.92                           | 69.36               | 1.0657439446366783
| benchmarks/requires01-a0le0-spec.k        | 55.63                           | 52.19               | 1.0659130101552023
| benchmarks/structarg00-spec.k             | 58.13                           | 54.53               | 1.066018705299835
| benchmarks/staticarray00-spec.k           | 57.03                           | 53.48               | 1.0663799551234108
| erc20/ds/allowance-spec.k                 | 135.64                          | 127.09              | 1.0672751593359036
| mcd/cat-exhaustiveness-spec.k             | 260.88                          | 244.2               | 1.0683046683046684
| mcd/vat-mului-pass-spec.k                 | 261.05                          | 243.92              | 1.0702279435880617
| erc20/hkg/balanceOf-spec.k                | 56.28                           | 52.53               | 1.0713877784123358
| bihu/forwardToHotWallet-failure-1-spec.k  | 140.08                          | 130.57              | 1.0728344949069466
| mcd/functional-spec.k                     | 619.42                          | 577.03              | 1.0734623849713187
| erc20/hkg/transfer-failure-1-spec.k       | 77.93                           | 72.54               | 1.0743038323683485
| benchmarks/encodepacked-keccak01-spec.k   | 56.34                           | 52.35               | 1.07621776504298
| benchmarks/ecrecover00-siginvalid-spec.k  | 109.53                          | 101.19              | 1.0824192113845241
| mcd/dai-symbol-pass-spec.k                | 67.77                           | 62.6                | 1.08258785942492
| erc20/hkg/transferFrom-failure-2-spec.k   | 100.64                          | 92.9                | 1.0833153928955865
| erc20/ds/balanceOf-spec.k                 | 60.54                           | 55.87               | 1.0835868981564347
| benchmarks/keccak00-spec.k                | 60.84                           | 56.14               | 1.083719273245458
| benchmarks/dynamicarray00-spec.k          | 56.72                           | 52.32               | 1.084097859327217
| benchmarks/staticloop00-a0lt10-spec.k     | 59.4                            | 54.6                | 1.0879120879120878
| benchmarks/overflow00-overflow-spec.k     | 54.07                           | 49.61               | 1.0899012295908084
| bihu/functional-spec.k                    | 128.93                          | 117.75              | 1.0949469214437368
| erc20/hkg/transfer-failure-2-spec.k       | 96.74                           | 87.69               | 1.1032044702930779
| mcd/flopper-file-pass-rough-spec.k        | 626.76                          | 563.4               | 1.1124600638977635
| benchmarks/ecrecover00-sigvalid-spec.k    | 137.16                          | 122.78              | 1.1171200521257534
| erc20/ds/transferFrom-success-1-spec.k    | 143.58                          | 125.11              | 1.1476300855247383
| functional/evm-int-simplifications-spec.k | 155.64                          | 134.67              | 1.1557139674760526
| erc20/hkg/allowance-spec.k                | 62.95                           | 54.35               | 1.158233670653174
| examples/solidity-code-spec.md            | 268.44                          | 229.12              | 1.17161312849162
| benchmarks/address00-spec.k               | 181.99                          | 150.79              | 1.2069102725644938
| benchmarks/storagevar02-nooverflow-spec.k | 79.16                           | 58.42               | 1.3550154056829853
| erc20/ds/approve-failure-spec.k           | 85.36                           | 58.98               | 1.4472702611054595
| erc20/hkg/transferFrom-failure-1-spec.k   | 283.61                          | 193.85              | 1.4630384317771474
| erc20/ds/totalSupply-spec.k               | 79.63                           | 54.31               | 1.4662124838887864
| benchmarks/storagevar00-spec.k            | 75.07                           | 50.79               | 1.478046859618035
| benchmarks/bytes00-spec.k                 | 132.6                           | 67.57               | 1.9624093532632827
| TOTAL                                     | 8853.380000000001               | 8260.609999999999   | 1.0717586231525278

**Review by jberthold — APPROVED** [review]
LGTM

**Comment by jberthold** [comment]
Test run with `PYTEST_PARALLEL=1`: 
### Kontrol

| Test                                      | sam-better-map-unification time | master-1b22ad4 time | (sam-better-map-unification/master-1b22ad4) time 
|-------------------------------------------|---------------------------------|---------------------|--------------------------------------------------
| BMCLoopsTest.test_countdown_concrete()    | 12.64                           | 13.18               | 0.9590288315629742                               
| MethodDisambiguateTest.test_method_call() | 32.27                           | 33.62               | 0.9598453301606188                               
| BlockParamsTest.testCoinBase()            | 38.03                           | 39.47               | 0.9635165948821891                               
| BytesTypeTest.test_bytes4(bytes4)         | 34.9                            | 33.64               | 1.0374554102259215                               
| BlockParamsTest.testFee(uint256)          | 42.94                           | 41.04               | 1.0462962962962963                               
| TOTAL                                     | 160.78                          | 160.95              | 0.9989437713575645  

:grey_exclamation:

**Comment by jberthold** [comment]
### KEVM
| Test                                     | 375-EXPERIMENT-z3-bindings time | master-1b22ad4 time | (375-EXPERIMENT-z3-bindings/master-1b22ad4) time 
|------------------------------------------|---------------------------------|---------------------|--------------------------------------------------
| mcd/vat-subui-pass-rough-spec.k          | 85.76                           | 154.59              | 0.5547577462966556                               
| mcd/vat-addui-pass-spec.k                | 86.0                            | 153.97              | 0.5585503669546016                               
| mcd/vat-mului-pass-spec.k                | 70.05                           | 119.47              | 0.5863396668619737                               
| mcd/vat-subui-fail-rough-spec.k          | 62.69                           | 105.76              | 0.5927571860816944                               
| mcd/vat-addui-fail-rough-spec.k          | 64.43                           | 107.95              | 0.5968503937007874                               
| mcd/vat-muluu-pass-spec.k                | 74.23                           | 121.84              | 0.609241628365069                                
| mcd/vat-slip-pass-rough-spec.k           | 125.76                          | 196.26              | 0.640782635279731                                
| mcd/vat-subui-pass-spec.k                | 143.42                          | 211.95              | 0.6766690257136116                               
| mcd/flipper-addu48u48-fail-rough-spec.k  | 47.44                           | 61.38               | 0.7728901922450309                               
| mcd/end-subuu-pass-spec.k                | 50.76                           | 65.26               | 0.7778118296046582                               
| mcd/vat-move-diff-rough-spec.k           | 115.59                          | 147.27              | 0.7848849052760236                               
| mcd/dai-adduu-fail-rough-spec.k          | 46.59                           | 57.98               | 0.8035529492928597                               
| mcd/cat-exhaustiveness-spec.k            | 97.05                           | 118.01              | 0.8223879332259978                               
| mcd/vat-deny-diff-fail-rough-spec.k      | 80.34                           | 86.05               | 0.9336432306798373                               
| mcd/dstoken-approve-fail-rough-spec.k    | 83.6                            | 88.93               | 0.9400652198358258                               
| bihu/forwardToHotWallet-success-1-spec.k | 51.85                           | 54.9                | 0.9444444444444445                               
| erc20/ds/transferFrom-success-1-spec.k   | 82.42                           | 86.19               | 0.9562594268476622                               
| mcd/flipper-bids-pass-rough-spec.k       | 113.7                           | 118.65              | 0.9582806573957017                               
| erc20/ds/transferFrom-success-2-spec.k   | 74.78                           | 77.84               | 0.9606885919835559                               
| erc20/hkg/transferFrom-failure-1-spec.k  | 69.58                           | 72.37               | 0.9614481138593339                               
| TOTAL                                    | 1626.0399999999997              | 2206.6200000000003  | 0.7368917167432542 

:tada:

**Pull request merged**
