### PR TITLE
Add `kore-rpc-dev` --- `kore-rpc` with `kore-rpc-booster`-like interface

### PR DESCRIPTION
**Pull request by geo2a**

### CODE REVIEW

**Review by jberthold — APPROVED** [review]
LGTM.
Dependencies could be cleaned up but this is fine for the purpose

**Comment by jberthold** [comment]
Should we run a few tests with the binary, too?

**Comment by geo2a** [comment]
@jberthold I'm testing `kore-rpc-dev` on `test-a-to-f` as suggested, but unfortunately the workflow fails on Linux. I do not really understand why though, the same script works fine locally. I'll investigate further tomorrow.

**Comment by jberthold** [comment]
> @jberthold I'm testing `kore-rpc-dev` on `test-a-to-f` as suggested, but unfortunately the workflow fails on Linux. I do not really understand why though, the same script works fine locally. I'll investigate further tomorrow.

https://github.com/runtimeverification/hs-backend-booster/actions/runs/6013238437/job/16310293317?pr=284#step:8:173 In the last run, the server did not start up cleanly, it probably failed to verify the definition for some reason(?).  Unfortunately we don't get the failure reason in the output, it is only in the tarball (maybe we can also do something about that in `kore-rpc` code?).

**Comment by jberthold** [comment]
One thing to check maybe (for additional data): What does the test do if we don't set a `SERVER` variable at all, i.e., if we use `kore-rpc-booster`? Then the definition would be loaded by both booster and kore-rpc code, and probably also fail to load in the latter.

**Pull request merged**
