### PR TITLE
194 add length field to binary kore format

### PR DESCRIPTION
**Pull request by jberthold**
Kore [version 1.2.0 introduces an 8-byte length field](https://github.com/runtimeverification/llvm-backend/commit/90ff252b58fe7727eed0c0afdad3b30d37766f62) (as part of the header).
* check that the version is supported (range 1.0 .. 1.2)
* read the length field if version >= 1.2
* calculate total byte length and check it while decoding the data block

### CODE REVIEW

**Comment by jberthold** [comment]
We should bump the version of K used by CI in the integration tests (nix) - I could not find the place where the version is stored, though.

**Review by goodlyrottenapple — COMMENTED** [review]
LGTM, will look into the K version in CI. there might be a bit of tweaking necessary since we now depend on booster in K, so there is a circular dependency, but I think it can be dealt with

**Review by geo2a — APPROVED** [review]

**Comment by jberthold** [comment]
> LGTM, will look into the K version in CI. there might be a bit of tweaking necessary since we now depend on booster in K, so there is a circular dependency, but I think it can be dealt with

It should not be too distinct from the circular dependency between k and haskell-backend... we can probably use the same derivation as over there.

**Comment by jberthold** [comment]
Merging this to unblock others - will try to follow up with the nix changes tomorrow.

**Pull request merged**
